name: Wauh
version: '${project.version}'
main: org.gecko.wauh.Main
description: Bo o o wa uh
commands:
  stopwauh:
    description: Stop removing the wauh
    usage: /stopwauhremoval
    permission: op
    permission-message: §cYou need to have operator permissions to run this command!
  setradiuslimit:
    description: Set the radius limit
    usage: /setradiuslimit <radius>
    permission: op
    permission-message: §cYou need to have operator permissions to run this command!
  toggleremovalview:
    description: Toggle the visibility of the removal
    usage: /toggleremovalview
    permission: op
    permission-message: §cYou need to have operator permissions to run this command!
  test:
    description: Test gui
    usage: /Test
    permission: op
    permission-message: §cYou need to have operator permissions to run this command!
  givecustomitems:
    description: give yourself a custom item
    usage: /givecustomitems [bucket/barrier/bedrock/tsunami/all]
    permission: op
    permission-message: §cYou need to have operator permissions to run this command!
  ench:
    description: enchant the item in your hand
    usage: /ench [enchantment] <level>
    permission: op
    permission-message: §cYou need to have operator permissions to run this command!