name: Qodana Code Check
on:
  push:
    branches:
      - '*'
jobs:
  qodana-code-scan:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Qodana Code Scan
        uses: JetBrains/qodana-action@v2023.3
        with:
          pr-mode: false
          args: --baseline,qodana.sarif.json,--apply-fixes
          push-fixes: pull-request
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QODANA_BRANCH: ${GITHUB_REF_NAME}

      - name: Upload Qodana results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}